### PR TITLE
Add Postgres 17 support

### PR DESCRIPTION
**Pull request by bstaeheli**
Postgres 17 now is available on alpine linux: https://pkgs.alpinelinux.org/package/edge/main/x86/postgresql17

### CODE REVIEW

**Comment by aine-etke** [comment]
Only for edge repo, while this image uses the latest stable one.

**Comment by bstaeheli** [comment]
@aine-etke, what does that mean? https://github.com/spantaleev/matrix-docker-ansible-deploy script wanted to update it's postgres to version 17, but the galaxy/backup_borg task does not run anymore and therefore the playbook fails.

`TASK [galaxy/backup_borg : Fail if detected Postgres version is unsupported] *****************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  msg: 'You cannot use borg backup with Postgres v17. If you are using an old Postgres version, consider upgrading - link to docs for upgrading Postgres: docs/maintenance-postgres.md#upgrading-postgresql HOWEVER, if you are using a new Postgres version, there is a high chance that the version is not supported by borg backup yet (supported versions: [''14'', ''15'', ''16'']). You can''t do anything with that, details: https://github.com/etkecc/borgmatic/pull/1'

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=386  changed=12   unreachable=0    failed=1    skipped=574  rescued=0    ignored=0   `

**Comment by spantaleev** [comment]
I wonder if we should switch borgmatic to `edge`, so that the gap can be closed sooner (this time and every time it happens in the future).

**Comment by aine-etke** [comment]
@bstaeheli playbok suggested you updating to the latest available postgres version, because that's the latest available postgres version.

BorgBackup is a separate component, that has its own requirements and restrictions

**Comment by Kuchenmampfer** [comment]
I think either moving this role to `edge` or stalling the postgres update in the postgres role until this one can support the new version would be nice for the future.

@bstaeheli as a temporal workaround, you can manually do the export yourself with
```
sudo /usr/bin/docker exec --env-file=/mash/postgres/env-postgres-psql mash-postgres /usr/local/bin/pg_dumpall -h mash-postgres > postgre.sql
```
and then disable the postgres export in the borg role and include `/home` to have the export backed up like this:
```
backup_borg_location_source_directories:
  - "{{ mash_playbook_base_path }}"
  - /home
backup_borg_postgresql_enabled: false
```
You can of course also automate the export with cron or a systemd timer, but I personally was to lazy to do that...

**Comment by aine-etke** [comment]
Postgres v17 is supported since https://github.com/etkecc/borgmatic/commit/c0368cd93f3c26cd55b400d348c536000176aff3

**Comment by Kuchenmampfer** [comment]
whoaaa, very nice thank you <3

**Pull request closed without merging**
